// client/src/dashboard/DashboardScreen.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import { MButton } from "@mctlhq/ui";
import DomainBar from "../components/DomainBar.vue";
import { calculateProgressStats, clearProgress } from "../services/progressStore";

defineProps<{
  onReviewMistakes: () => void;
  onStartPractice: () => void;
}>();

const stats = ref(calculateProgressStats());
const weakestDomain = computed(() => {
  const attempted = stats.value.domainProgress.filter((domain) => domain.attemptedQuestions > 0);
  return attempted.sort((a, b) => a.accuracy - b.accuracy)[0] ?? null;
});

function handleClearHistory() {
  if (window.confirm("Are you sure you want to clear your learning progress and mistake history?")) {
    clearProgress();
    stats.value = calculateProgressStats();
  }
}
</script>

<template>
  <section class="progress-screen page-shell">
    <div class="progress-grid">
      <div>
        <div class="readiness-heading">
          <strong>{{ stats.overallAccuracy }}%</strong>
          <span>{{ stats.totalAttempted > 0 ? "Based on attempted questions" : "Start practicing to build your baseline" }}</span>
        </div>
        <p class="section-marker">Overall readiness</p>

        <h1>Domain readiness</h1>
        <div class="domain-bars">
          <DomainBar
            v-for="domain in stats.domainProgress"
            :key="domain.domainId"
            :label="domain.domainTitle"
            :value="domain.accuracy"
            :detail="`${domain.attemptedQuestions}/${domain.totalQuestions}`"
          />
        </div>
      </div>

      <aside class="progress-summary" aria-label="Progress details">
        <dl>
          <div>
            <dt>Attempted</dt>
            <dd>{{ stats.totalAttempted }}/{{ stats.totalBankQuestions }}</dd>
          </div>
          <div>
            <dt>Correct</dt>
            <dd>{{ stats.totalCorrect }}</dd>
          </div>
          <div>
            <dt>Open mistakes</dt>
            <dd>{{ stats.totalMistakes }}</dd>
          </div>
        </dl>

        <div v-if="weakestDomain" class="weakest-card">
          <span>Weakest domain</span>
          <strong>{{ weakestDomain.domainTitle }}</strong>
          <button v-if="stats.totalMistakes > 0" type="button" @click="onReviewMistakes">
            Review {{ stats.totalMistakes }} mistakes <span aria-hidden="true">→</span>
          </button>
          <button v-else type="button" @click="onStartPractice">Continue practice <span aria-hidden="true">→</span></button>
        </div>

        <MButton type="button" variant="ghost" size="sm" class="reset-progress" @click="handleClearHistory">
          Reset progress history
        </MButton>
      </aside>
    </div>
  </section>
</template>

<style scoped>
.progress-grid {
  display: grid;
  grid-template-columns: minmax(0, 1fr) 18.75rem;
  gap: 3rem;
}

.readiness-heading {
  display: flex;
  align-items: baseline;
  gap: 1.25rem;
}

.readiness-heading strong {
  font-family: var(--font-mono);
  font-size: clamp(3rem, 7vw, 4rem);
  font-weight: 300;
  line-height: 1;
}

.readiness-heading span {
  color: var(--surface-fg-subtle);
  font-family: var(--font-mono);
  font-size: 0.75rem;
}

.section-marker,
.progress-summary dt,
.weakest-card > span {
  font-family: var(--font-mono);
  font-size: 0.72rem;
  font-weight: 600;
  letter-spacing: 0.08em;
  text-transform: uppercase;
}

.section-marker {
  margin: 0.6rem 0 2rem;
  color: var(--surface-fg-subtle);
}

.progress-screen h1 {
  margin: 0 0 1.35rem;
  color: var(--surface-fg-subtle);
  font-family: var(--font-mono);
  font-size: 0.75rem;
  letter-spacing: 0.08em;
  text-transform: uppercase;
}

.domain-bars {
  display: grid;
  gap: 1.1rem;
}

.progress-summary dl {
  display: grid;
  gap: 1rem;
  margin: 0 0 1.4rem;
  padding: 0 0 1.4rem;
  border-bottom: 1px solid var(--surface-line);
}

.progress-summary dl div {
  display: flex;
  align-items: baseline;
  justify-content: space-between;
  gap: 1rem;
}

.progress-summary dt {
  color: var(--surface-fg-subtle);
}

.progress-summary dd {
  margin: 0;
  font-family: var(--font-mono);
  font-size: 1.1rem;
  font-weight: 600;
}

.weakest-card {
  display: grid;
  gap: 0.6rem;
  padding: 1rem 1.1rem;
  border: 1px solid var(--surface-line);
  border-radius: var(--mctl-radius-lg);
  background: var(--surface-elevated);
}

.weakest-card > span {
  color: var(--surface-fg-subtle);
}

.weakest-card strong {
  font-size: 0.9rem;
}

.weakest-card button {
  padding: 0;
  border: 0;
  background: transparent;
  color: var(--accent);
  font-family: var(--font-mono);
  font-size: 0.75rem;
  font-weight: 600;
  text-align: left;
  cursor: pointer;
}

.reset-progress {
  margin-top: 1.25rem;
  color: var(--surface-fg-subtle) !important;
}

@media (max-width: 800px) {
  .progress-grid {
    grid-template-columns: 1fr;
    gap: 2.5rem;
  }
}
</style>

// client/src/dashboard/DashboardScreen.tsx
import { useState } from "react";
import { calculateProgressStats, clearProgress } from "../services/progressStore";
import "./DashboardScreen.css";

interface DashboardScreenProps {
  onReviewMistakes: () => void;
  onStartPractice: () => void;
}

export function DashboardScreen({ onReviewMistakes, onStartPractice }: DashboardScreenProps) {
  const [stats, setStats] = useState(() => calculateProgressStats());

  const handleClearHistory = () => {
    if (window.confirm("Are you sure you want to clear your learning progress and mistake history?")) {
      clearProgress();
      setStats(calculateProgressStats());
    }
  };

  return (
    <div className="dashboard-container">
      <div className="dashboard-header">
        <h2>Learner Progress & Mastery Dashboard</h2>
        <p className="dashboard-subtitle">
          Track your overall performance and domain-by-domain readiness across the 4 exam domains.
        </p>
      </div>

      <div className="stats-cards-grid">
        <div className="stat-card">
          <div className="stat-value">{stats.overallAccuracy}%</div>
          <div className="stat-label">Overall Accuracy</div>
        </div>

        <div className="stat-card">
          <div className="stat-value">
            {stats.totalAttempted} / {stats.totalBankQuestions}
          </div>
          <div className="stat-label">Questions Attempted</div>
        </div>

        <div className="stat-card">
          <div className="stat-value text-warning">{stats.totalMistakes}</div>
          <div className="stat-label">Reviewable Mistakes</div>
        </div>
      </div>

      <div className="dashboard-actions">
        {stats.totalMistakes > 0 ? (
          <button className="btn btn-primary" onClick={onReviewMistakes}>
            Review Mistakes ({stats.totalMistakes})
          </button>
        ) : (
          <button className="btn btn-secondary" onClick={onStartPractice}>
            Start Full Practice Bank
          </button>
        )}
        <button className="btn btn-outline-danger" onClick={handleClearHistory}>
          Reset Progress History
        </button>
      </div>

      <div className="domain-breakdown-section">
        <h3>Domain Mastery Breakdown</h3>
        <div className="domain-cards-list">
          {stats.domainProgress.map((domain) => (
            <div className="domain-card" key={domain.domainId}>
              <div className="domain-card-header">
                <h4>{domain.domainTitle}</h4>
                <span className="domain-accuracy-badge">{domain.accuracy}% Accuracy</span>
              </div>

              <div className="progress-bar-track">
                <div
                  className="progress-bar-fill"
                  style={{
                    width: `${domain.accuracy}%`,
                    backgroundColor:
                      domain.accuracy >= 80 ? "#2e7d32" : domain.accuracy >= 60 ? "#ed6c02" : "#d32f2f",
                  }}
                />
              </div>

              <div className="domain-card-meta">
                <span>
                  Attempted: {domain.attemptedQuestions} / {domain.totalQuestions} questions
                </span>
                <span>Correct: {domain.correctQuestions}</span>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
