// client/src/exam/components/RestrictedMarkdown.vue
<script setup lang="ts">
import { computed } from "vue";
import { parseRestrictedMarkdown } from "../markdown";

const props = defineProps<{ text: string }>();

// Never v-html: parseRestrictedMarkdown's segments render as plain text
// nodes, matching the invariant the React version documented -- raw markup
// in a question stem/option/explanation can never execute.
const segments = computed(() => parseRestrictedMarkdown(props.text));
</script>

<template>
  <template v-for="(segment, index) in segments" :key="index">
    <code v-if="segment.type === 'code'">{{ segment.value }}</code>
    <span v-else>{{ segment.value }}</span>
  </template>
</template>

// client/src/exam/components/RestrictedMarkdown.tsx
import { parseRestrictedMarkdown } from "../markdown";

/** Renders restricted Markdown (backtick code spans only) as React text nodes -- never dangerouslySetInnerHTML. */
export function RestrictedMarkdown({ text }: { text: string }) {
  const segments = parseRestrictedMarkdown(text);
  return (
    <>
      {segments.map((segment, index) =>
        segment.type === "code" ? (
          <code key={index}>{segment.value}</code>
        ) : (
          <span key={index}>{segment.value}</span>
        ),
      )}
    </>
  );
}
